/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Backpropagation;

import static java.lang.Math.random;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import static java.sql.Types.NULL;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zorokunti
 */
public class MainBPNN extends javax.swing.JFrame {

    /**
     * Creates new form MainBPNN
     */
    
    ArrayList<Double> mean= new ArrayList<Double>();
    ArrayList<Double> variance= new ArrayList<Double>();
    ArrayList<Double> skewness= new ArrayList<Double>();
    ArrayList<Double> kurtosis= new ArrayList<Double>();
    ArrayList<Double> entrophy= new ArrayList<Double>();
    ArrayList<Double> target= new ArrayList<Double>();
    
    
    
    ArrayList<Double> x1= new ArrayList<Double>();
    ArrayList<Double> x2= new ArrayList<Double>();
    ArrayList<Double> x3= new ArrayList<Double>();
    ArrayList<Double> x4= new ArrayList<Double>();
    ArrayList<Double> x5= new ArrayList<Double>();
    ArrayList<Double> xt= new ArrayList<Double>();
    
    Double minM, maxM, minV, maxV, minS, maxS, minK, maxK, minE, maxE, minT, maxT;

    Random random = new Random();
    
    

    
    
    
    public MainBPNN() {
      
    
        
        initComponents(); 
        load_table_pengguna();
        load_table_pelatihan();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        et_nama = new javax.swing.JTextField();
        et_jenis_kelamin = new javax.swing.JTextField();
        et_alamat = new javax.swing.JTextField();
        btn_tambah_pengguna = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pengguna = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        et_id_pengguna = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        training = new javax.swing.JButton();
        btn_normalisasi = new javax.swing.JButton();
        test = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_pelatihan = new javax.swing.JTable();
        et_learning_rate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        et_max_epoh = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        et_min_error = new javax.swing.JTextField();
        lbl_test = new javax.swing.JLabel();
        btn_reload_normalisasi = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_dynamic = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        et_mean = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        et_entrophy = new javax.swing.JTextField();
        et_kurtosis = new javax.swing.JTextField();
        et_variance = new javax.swing.JTextField();
        et_skewness = new javax.swing.JTextField();
        btn_identifikasi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nama Lengkap");

        jLabel3.setText("Tanggal  Lahir");

        jLabel5.setText("Jenis Kelamin");

        jLabel6.setText("Alamat");

        et_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et_namaActionPerformed(evt);
            }
        });

        et_jenis_kelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et_jenis_kelaminActionPerformed(evt);
            }
        });

        et_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et_alamatActionPerformed(evt);
            }
        });

        btn_tambah_pengguna.setText("Tambah");
        btn_tambah_pengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_penggunaActionPerformed(evt);
            }
        });

        tbl_pengguna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_pengguna);

        jLabel12.setText("ID Pengguna");

        et_id_pengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et_id_penggunaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_tambah_pengguna))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(et_jenis_kelamin, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(et_nama, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(et_id_pengguna, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(et_alamat))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(et_id_pengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(et_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(et_jenis_kelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(et_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_tambah_pengguna)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(" Data Pelatihan");

        training.setText("Training BPNN");
        training.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainingActionPerformed(evt);
            }
        });

        btn_normalisasi.setText("Normalisasi");
        btn_normalisasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_normalisasiActionPerformed(evt);
            }
        });

        test.setText("Tes Fungsi");
        test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testActionPerformed(evt);
            }
        });

        tbl_pelatihan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_pelatihan);

        et_learning_rate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        et_learning_rate.setText("0.2");
        et_learning_rate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et_learning_rateActionPerformed(evt);
            }
        });

        jLabel9.setText("Learning Rate");

        et_max_epoh.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        et_max_epoh.setText("20000");

        jLabel10.setText("Max. Epoh");

        jLabel11.setText("Min. Error");

        et_min_error.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        et_min_error.setText("0.0001");

        btn_reload_normalisasi.setText("R");
        btn_reload_normalisasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reload_normalisasiActionPerformed(evt);
            }
        });

        tbl_dynamic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbl_dynamic);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 937, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_reload_normalisasi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(291, 291, 291)
                                .addComponent(lbl_test)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(et_learning_rate, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(et_max_epoh, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(et_min_error, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(btn_normalisasi)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(training)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(test))))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(et_learning_rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(et_max_epoh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(et_min_error, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_normalisasi)
                    .addComponent(training)
                    .addComponent(test)
                    .addComponent(btn_reload_normalisasi))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(511, 511, 511)
                .addComponent(lbl_test, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Data Pengguna");

        et_mean.setText("0.1");

        jLabel1.setText("Mean");

        jLabel13.setText("Variance");

        jLabel14.setText("Skewness");

        jLabel15.setText("Kurtosis");

        jLabel16.setText("Entrophy");

        et_entrophy.setText("0.98731");

        et_kurtosis.setText("0.81181");

        et_variance.setText("0.97108");

        et_skewness.setText("0.86554");
        et_skewness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et_skewnessActionPerformed(evt);
            }
        });

        btn_identifikasi.setText("Identifikasi");
        btn_identifikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_identifikasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn_identifikasi)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel16)
                                                .addComponent(jLabel15))
                                            .addGap(27, 27, 27))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(et_skewness)
                                        .addComponent(et_kurtosis)
                                        .addComponent(et_entrophy)
                                        .addComponent(et_variance)
                                        .addComponent(et_mean, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1830, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(et_mean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(et_variance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(et_skewness, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(et_kurtosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(et_entrophy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(29, 29, 29)
                        .addComponent(btn_identifikasi)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1122, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void et_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_et_namaActionPerformed

    private void et_jenis_kelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et_jenis_kelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_et_jenis_kelaminActionPerformed

    private void et_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_et_alamatActionPerformed

    private void btn_tambah_penggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_penggunaActionPerformed
        // TODO add your handling code here:
        
        String id_pengguna = et_id_pengguna.getText();
        String nama = et_nama.getText();
        String tgl_lahir = "2018-02-02";
        String jk = "L";
        String alamat = et_alamat.getText();
        
        
        /*
        Function fc = new Function();
        String query = ""+id+","+nama+","+tgl_lahir+","+alamat+","+pekerjaan+","+link+"";
        fc.addPengguna(query);
        System.out.println(""+query);
        */
        
         try {
            String sql = "INSERT INTO tbl_pengguna VALUES ('"+id_pengguna+"','"+nama+"','"+tgl_lahir+"','"+jk+"','"+alamat+"')";
            java.sql.Connection conn=(Connection)Connect.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
//            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (Exception e) {
  //          JOptionPane.showMessageDialog(null, e.getMessage());
        }
         
        
        load_table_pengguna();
    }//GEN-LAST:event_btn_tambah_penggunaActionPerformed

    private void btn_normalisasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_normalisasiActionPerformed
        // TODO add your handling code here:
        normalisasi();
    }//GEN-LAST:event_btn_normalisasiActionPerformed

    private void testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testActionPerformed
        // TODO add your handling code here:
        //trainingBPNN();
        //System.out.println("percobaan = "+trainingBPNN());
        
        
    }//GEN-LAST:event_testActionPerformed

    private void et_learning_rateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et_learning_rateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_et_learning_rateActionPerformed

    private void et_id_penggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et_id_penggunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_et_id_penggunaActionPerformed

    private void trainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainingActionPerformed
        // TODO add your handling code here:
        trainingBPNN();
    }//GEN-LAST:event_trainingActionPerformed

    private void btn_identifikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_identifikasiActionPerformed
        // TODO add your handling code here:
        pengujian();
    }//GEN-LAST:event_btn_identifikasiActionPerformed

    private void et_skewnessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et_skewnessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_et_skewnessActionPerformed

    private void btn_reload_normalisasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reload_normalisasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_reload_normalisasiActionPerformed

    
    
    private void load_table_pengguna(){
        // membuat tampilan model tabel
        DefaultTableModel modelpengguna = new DefaultTableModel();
        modelpengguna.addColumn("ID Pengguna");
        modelpengguna.addColumn("Nama");
        modelpengguna.addColumn("Jenis Kelamin");
        modelpengguna.addColumn("Alamat");
        
        //menampilkan data database kedalam tabel
        try {
            int no=1;
            String sql = "select * from tbl_pengguna";
            java.sql.Connection conn=(Connection)Connect.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                modelpengguna.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(4),res.getString(5)});
            }
            tbl_pengguna.setModel(modelpengguna);
            stm.close();
        } catch (Exception e ) {
        }
    }
    
    
    
    private void load_table_pelatihan(){
        // membuat tampilan model tabel
        DefaultTableModel modell = new DefaultTableModel();
       
        modell.addColumn("No");
        modell.addColumn("Mean");
        modell.addColumn("Variance");
        modell.addColumn("Skewness");
        modell.addColumn("Kurtosis");
        modell.addColumn("Entrophy");
        modell.addColumn("Target");
        
        //menampilkan data database kedalam tabel
        try {
            int no=1;
            String sql = "select * from tbl_pelatihan";
            java.sql.Connection conn=(Connection)Connect.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                modell.addRow(new Object[]{no,res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(2)});
                no++;
            }
           // tbl_pelatihan.setAutoResizeMode(1);
            tbl_pelatihan.setModel(modell);
            tbl_pelatihan.setAutoscrolls(false);
            stm.close();
       
        } catch (Exception e) {
        }
    }
    
    public void normalisasi(){
        
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
       
        model.addColumn("Mean");
        model.addColumn("Variance");
        model.addColumn("Skewness");
        model.addColumn("Kurtosis");
        model.addColumn("Entrophy");
        model.addColumn("Target");
        
        try {
            int no=0;
            String sql = "select * from tbl_pelatihan";
            java.sql.Connection conn=(Connection)Connect.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            
            while(res.next()){
                //model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
                
                mean.add(res.getDouble(3));
                variance.add(res.getDouble(4));
                skewness.add(res.getDouble(5));
                kurtosis.add(res.getDouble(6));
                entrophy.add(res.getDouble(7));
                target.add(res.getDouble(2));
                
               // model.addRow(new Object[]{mean.get(no).toString(),variance.get(no).toString(),skewness.get(no).toString()
                 //       ,kurtosis.get(no).toString(),entrophy.get(no).toString(),target.get(no).toString()});
                
                no++;
                
            
            }
            stm.close();
            
            for(int a = 0; a<no; a++){
                
                 minM = Collections.min(mean);
                 maxM = Collections.max(mean);
                 minV = Collections.min(variance);
                 maxV = Collections.max(variance);
                 minS = Collections.min(skewness);
                 maxS = Collections.max(skewness);
                 minK = Collections.min(kurtosis);
                 maxK = Collections.max(kurtosis);
                 minE = Collections.min(entrophy);
                 maxE = Collections.max(entrophy);
                 minT = Collections.min(target);
                 maxT = Collections.max(target);
                
                 
                Function fc = new Function();
                DecimalFormat df = new DecimalFormat("#.#####");
                double ex1 = fc.normalisasi(mean.get(a),minM,maxM);
                double ex2 = fc.normalisasi(variance.get(a),minV,maxV);
                double ex3 = fc.normalisasi(skewness.get(a),minS,maxS);
                double ex4 = fc.normalisasi(kurtosis.get(a),minK,maxK);
                double ex5 = fc.normalisasi(entrophy.get(a),minE,maxE);
                
                x1.add(Double.valueOf(df.format(ex1)));
                
                x2.add(Double.valueOf(df.format(ex2)));
                
                x3.add(Double.valueOf(df.format(ex3)));
                
                x4.add(Double.valueOf(df.format(ex4)));
                
                x5.add(Double.valueOf(df.format(ex5)));
                
                xt.add(target.get(a));
                
               
                model.addRow(new Object[]{x1.get(a).toString(),x2.get(a).toString(),x3.get(a).toString()
                        ,x4.get(a).toString(),x5.get(a).toString(),xt.get(a).toString()});
                
            }
            tbl_dynamic.setModel(model);
        } catch (Exception e) {
        }
        
    }
    
    
    public void  trainingBPNN(){
        
        double alfa = Double.parseDouble(et_learning_rate.getText());
        int max_iterasi = Integer.parseInt(et_max_epoh.getText());
        double maxError = Double.parseDouble(et_min_error.getText());
        
        bpnn bp = new bpnn(alfa);
        Data dt = new Data();
        
        double [][] data = dt.getDataLatih();
        
        double bobotBaru [][]=bp.backpro(data, max_iterasi,maxError);
        
        
        System.out.println("");
        
        try {
            
                    String truncate = "TRUNCATE TABLE bobot";
                    String que = "insert into bobot (v0,v1,v2,v3,v4,w)"+" values (?,?,?,?,?,?)";
                    java.sql.Connection conn=(Connection)Connect.configDB();
                    
                    PreparedStatement tc = conn.prepareStatement(truncate);
                    tc.execute();
                    
                    PreparedStatement pst = conn.prepareStatement(que);
                    for (int l = 0; l < bobotBaru.length; l++) {
                        for (int k = 0; k < 1; k++) {
                        pst.setDouble(1, bobotBaru[l][0]);
                        pst.setDouble(2, bobotBaru[l][1]);
                        pst.setDouble(3, bobotBaru[l][2]);
                        pst.setDouble(4, bobotBaru[l][3]);
                        pst.setDouble(5, bobotBaru[l][4]);
                        pst.setDouble(6, bobotBaru[l][5]);
                       pst.executeUpdate();
                        }
                    }
                } catch (Exception e) {
                }
        
        
        System.out.println("panjangnya adalah"+bobotBaru.length);
        System.out.println("MATRIK BOBOT DAN BIAS TERBARU ");
       
        for(int i=0;i<bobotBaru.length;i++){
            for(int j=0;j<bobotBaru[0].length-1;j++){
                //System.out.println("ini adalah bobot baru input "+i+"j="+j);
                System.out.print(bobotBaru[i][j]+" ");
                
            }
            System.out.println(""); 
        }
        
        for(int i=0;i<bobotBaru.length;i++){
            for(int j=0;j<bobotBaru[0].length;j++){
               // System.out.println("i="+i+"j="+j);
                System.out.print(bobotBaru[i][j]+" ");
                
            }
            System.out.println(""); 
        }
       
    }
    
    public void pengujian(){
        double alfa = Double.parseDouble(et_learning_rate.getText());
        bpnn bp = new bpnn(alfa);
        Data dt = new Data();
        
        
      
        double x1,x2,x3,x4,x5;
        
        x1 = Double.parseDouble(et_mean.getText());
        x2 = Double.parseDouble(et_variance.getText());
        x3 = Double.parseDouble(et_skewness.getText());
        x4 = Double.parseDouble(et_kurtosis.getText());
        x5 = Double.parseDouble(et_entrophy.getText());
        
        double [][] xx = new double[1][5];
        double [][] bobothidden = dt.getBobotHidden();
        double [] bobotbias = dt.getBias();
        double [] bobotoutput = dt.getBobotOutput();
        
        for (int i = 0; i < 1; i++) {
            for (int j = 0; j<1; j++) {
                xx[0][0]=x1;
                xx[0][1]=x2;
                xx[0][2]=x3;
                xx[0][3]=x4;
                xx[0][4]=x5;
            }
        }
        
        
       
        double y = bp.feedForward(xx, 0, bobothidden, bobotbias, bobotoutput);
        System.out.println(y);
         double [][] compareUji = dt.getCompareUji();
        
        double start = y;
        
        
        List<Double> nilaiCompare = new ArrayList<>();
       
          for (int i = 0; i < compareUji.length; i++) {
              for (int j = 0; j < compareUji[0].length-1; j++) {
                  nilaiCompare.add(compareUji[i][j]);
              }
          }

        Collections.sort(nilaiCompare);

        double nearest = 0;

        for (double i : nilaiCompare)
        {
            if (i <= start) {
                nearest = i;
                
            }
        }
        //System.out.println(nearest);
        dt.getUser(nearest);
                  
    }
   
    

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainBPNN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainBPNN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainBPNN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainBPNN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainBPNN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_identifikasi;
    private javax.swing.JButton btn_normalisasi;
    private javax.swing.JButton btn_reload_normalisasi;
    private javax.swing.JButton btn_tambah_pengguna;
    private javax.swing.JTextField et_alamat;
    private javax.swing.JTextField et_entrophy;
    private javax.swing.JTextField et_id_pengguna;
    private javax.swing.JTextField et_jenis_kelamin;
    private javax.swing.JTextField et_kurtosis;
    private javax.swing.JTextField et_learning_rate;
    private javax.swing.JTextField et_max_epoh;
    private javax.swing.JTextField et_mean;
    private javax.swing.JTextField et_min_error;
    private javax.swing.JTextField et_nama;
    private javax.swing.JTextField et_skewness;
    private javax.swing.JTextField et_variance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_test;
    private javax.swing.JTable tbl_dynamic;
    private javax.swing.JTable tbl_pelatihan;
    private javax.swing.JTable tbl_pengguna;
    private javax.swing.JButton test;
    private javax.swing.JButton training;
    // End of variables declaration//GEN-END:variables
}
